apiVersion: v1
data:
  application.yml: |-
    ---
    broker:
      object-endpoint: "https://object.ecstestdrive.com"
      management-endpoint: "https://portal.ecstestdrive.com"
      namespace: <NAMESPACE>
      replication-group: <REP_GROUP>
      prefix: <PREFIX>
    catalog:
      services:
      -
        active: true
        bindable: true
        description: "Elastic Cloud S3 Object Storage Bucket"
        id: f3cbab6a-5172-4ff1-a5c7-72990f0ce2aa
        repository-service: true
        metadata:
          displayName: ecs-bucket
          documentationUrl: "https://community.emc.com/docs/DOC-45012"
          imageUrl: "http://www.emc.com/images/products/header-image-icon-ecs.png"
          longDescription: "Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3."
          providerDisplayName: "Dell EMC"
          supportUrl: "http://www.emc.com/products-solutions/trial-software-download/ecs.htm"
        name: ecs-bucket
        plan-updatable: true
        plans:
        -
          description: "Free Trial"
          free: true
          id: 8e777d49-0a78-4cf4-810a-b5f5173b019d
          metadata:
            bullets:
            - "Shared object storage"
            - "5 GB Storage"
            - "S3 protocol access"
            costs:
            -
              amount:
                usd: 0.0
              unit: MONTHLY
          name: 5gb
          service-settings:
            quota:
              limit: 5
              warn: 4
          repository-plan: true
        -
          description: "Pay per GB for Month"
          id: 89d20694-9ab0-4a98-bc6a-868d6d4ecf31
          metadata:
            bullets:
            - "Shared object storage"
            - "Unlimited Storage"
            - "S3 protocol access"
            costs:
            -
              amount:
                usd: 0.03
              unit: "PER GB PER MONTH"
          name: unlimited
        service-settings:
          access-during-outage: true
          ado-read-only: true
          head-type: s3
          service-type: bucket
        tags:
        - s3
        - bucket
        type: bucket
      -
        active: false
        bindable: true
        description: "Elastic Cloud S3 Object Storage File Accessible Bucket"
        repository-service: false
        id: 9052313c-20b2-47de-900f-6e8b04fafcca
        metadata:
          displayName: ecs-file-bucket
          documentationUrl: "https://community.emc.com/docs/DOC-45012"
          imageUrl: "http://www.emc.com/images/products/header-image-icon-ecs.png"
          longDescription: "Dell EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3 or NFS."
          providerDisplayName: "Dell EMC"
          supportUrl: "http://www.emc.com/products-solutions/trial-software-download/ecs.htm"
        name: ecs-file-bucket
        plan-updatable: true
        plans:
        -
          description: "Free Trial"
          free: true
          id: b7c3f0b0-6867-44e3-b1b9-b255852010b3
          metadata:
            bullets:
            - "Shared object storage"
            - "5 GB Storage"
            - "S3 protocol and HDFS access"
            costs:
            -
              amount:
                usd: 0.0
              unit: MONTHLY
          name: 5gb
          service-settings:
            file-accessible: true
            quota:
              limit: 5
              warn: 4
        -
          description: "Pay per GB for Month"
          id: 285817bc-e73d-4bb4-bd5d-aebe54ef792f
          metadata:
            bullets:
            - "Shared object storage"
            - "Unlimited Storage"
            - "S3 protocol and HDFS access"
            costs:
            -
              amount:
                usd: 0.03
              unit: "PER GB PER MONTH"
          name: unlimited
        requires:
        - volume_mount
        service-settings:
          access-during-outage: true
          file-accessible: true
          head-type: s3
          service-type: bucket
        tags:
        - s3
        - bucket
        - nfs
        - hdfs
        type: bucket
    server:
      max-http-header-size: 32KB
    security:
      user:
        name: admin
        password: somethingsecure
    spring:
      profiles: default
kind: ConfigMap
metadata:
  creationTimestamp: "2019-07-26T02:22:13Z"
  name: ecs-broker
  namespace: default
  resourceVersion: "74682"
  selfLink: /api/v1/namespaces/default/configmaps/application-yaml
  uid: 871a8dfa-3384-4508-b1e2-03820124db5f
